name:                cardano-client
version:             1.0.0
github:              "KtorZ/cardano-ogmios"
license:             MPL-2.0
author:              "KtorZ <matthias.benkort@gmail.com>"
maintainer:          "matthias.benkort@gmail.com"
copyright:           "2020 KtorZ"
description:         Please see the README on GitHub at <https://github.com/KtorZ/ogmios>
synopsis:            Utilities to build a cardano client using the Ouroboros mini-protocols
category:            Cardano

dependencies:
- base >= 4.7 && < 5

flags:
  production:
    description: Compile executables for production.
    default: False
    manual: True

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
  when:
    condition: flag(production)
    ghc-options:
    - -Werror
    - -O2
  dependencies:
    - aeson
    - async
    - binary
    - bytestring
    - cardano-binary
    - cardano-crypto-class
    - cardano-crypto-praos
    - cardano-crypto-wrapper
    - cardano-ledger
    - cardano-prelude
    - cardano-slotting
    - cborg
    - containers
    - contra-tracer
    - io-sim-classes
    - iohk-monitoring
    - memory
    - network-mux
    - optparse-applicative
    - ouroboros-consensus
    - ouroboros-consensus-byron
    - ouroboros-consensus-cardano
    - ouroboros-consensus-shelley
    - ouroboros-network
    - ouroboros-network-framework
    - process
    - safe
    - scientific
    - shelley-spec-ledger
    - stm
    - text
    - time
    - typed-protocols
    - typed-protocols-examples
    - unordered-containers
    - vector
