# Set of default configuration re-used across the project and its sub-modules.
#
# The choices below are quite opinionated, mostly derived from:
#
#   https://github.com/commercialhaskell/rio

---

_default-extensions: !include ".stylish-haskell.yaml"

ghc-options:
  library: &ghc-options-lib
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints

  test: &ghc-options-test
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
