name:                ogmios
version:             1.0.0
github:              "KtorZ/cardano-ogmios"
license:             MPL-2.0
author:              "KtorZ <matthias.benkort@gmail.com>"
maintainer:          "matthias.benkort@gmail.com"
copyright:           "2020 KtorZ"
description:         Please see the README on GitHub at <https://github.com/KtorZ/ogmios>
synopsis:            A JSON-WSP WebSocket client for cardano-node
category:            Web

extra-source-files:
- README.md
- ogmios.wsp.json
- Dockerfile
- docker-compose.yml
- docs/COMMAND_LINE.md

dependencies:
- base >= 4.7 && < 5

flags:
  production:
    description: Compile executables for production.
    default: False
    manual: True

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
  when:
    condition: flag(production)
    ghc-options:
    - -Werror
    - -O2
  dependencies:
    - aeson
    - async
    - bech32
    - bech32-th
    - binary
    - bytestring
    - cardano-binary
    - cardano-crypto-class
    - cardano-crypto-praos
    - cardano-crypto-wrapper
    - cardano-ledger
    - cardano-prelude
    - cardano-slotting
    - cborg
    - containers
    - contra-tracer
    - file-embed
    - io-sim-classes
    - iohk-monitoring
    - iproute
    - memory
    - network-mux
    - optparse-applicative
    - ouroboros-consensus
    - ouroboros-consensus-byron
    - ouroboros-consensus-cardano
    - ouroboros-consensus-shelley
    - ouroboros-network
    - ouroboros-network-framework
    - process
    - safe
    - shelley-spec-ledger
    - stm
    - template-haskell
    - text
    - time
    - typed-protocols
    - typed-protocols-examples
    - vector
    - wai
    - wai-routes
    - websockets

executables:
  ogmios:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Wcompat
    - -fwarn-redundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    when:
      condition: flag(production)
      ghc-options:
      - -Werror
      - -O2
      - -with-rtsopts=-A250m
    dependencies:
    - async
    - contra-tracer
    - directory
    - http-types
    - ogmios
    - text
    - wai-websockets
    - warp
    - websockets

tests:
  unit:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options:
    - -Wcompat
    - -fwarn-redundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - aeson-pretty
    - bytestring
    - cardano-ledger
    - cardano-ledger-test
    - generic-arbitrary
    - hedgehog-quickcheck
    - hjsonschema
    - hspec
    - ogmios
    - ouroboros-consensus-byron
    - ouroboros-consensus-byron-test
    - ouroboros-network
    - QuickCheck
    - text
