resolver: snapshot.yaml

# Generate files required by weeder
# See https://github.com/ndmitchell/weeder/issues/53
ghc-options: {"$locals": -ddump-to-file -ddump-hi}

packages:
- .

extra-deps:
- wai-routes-0.10.4
- git: https://github.com/KtorZ/ouroboros-network
  commit: a551cdd035cb4be8e856ef905c268f01e00029a5
  subdirs:
  - ouroboros-network
  - ouroboros-consensus
