_config: !include "../.hpack.config.yaml"

name:                ogmios
version:             2.0.0
github:              "KtorZ/cardano-ogmios"
license:             MPL-2.0
author:              "KtorZ <matthias.benkort@gmail.com>"
maintainer:          "matthias.benkort@gmail.com"
copyright:           "2020 KtorZ"
description:         Please see the README on GitHub at <https://github.com/KtorZ/ogmios>
synopsis:            A JSON-WSP WebSocket client for cardano-node
category:            Web

extra-source-files:
- LICENSE
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

default-extensions: *default-extensions

flags:
  production:
    description: Compile executables for production.
    default: False
    manual: True

library:
  source-dirs: src
  ghc-options: *ghc-options-lib
  when:
    condition: flag(production)
    ghc-options:
    - -Werror
    - -O2
  dependencies:
    - aeson
    - async
    - base58-bytestring
    - bech32
    - bech32-th
    - bytestring
    - cardano-api
    - cardano-binary
    - cardano-client
    - cardano-crypto-class
    - cardano-crypto-wrapper
    - cardano-ledger
    - cardano-prelude
    - cardano-slotting
    - cborg
    - containers
    - contra-tracer
    - directory
    - ekg-core
    - file-embed
    - git-th
    - http-types
    - io-sim-classes
    - iohk-monitoring
    - iproute
    - json-wsp
    - manufacture
    - memory
    - optparse-applicative
    - optparse-applicative
    - ouroboros-consensus
    - ouroboros-consensus-byron
    - ouroboros-consensus-cardano
    - ouroboros-consensus-shelley
    - ouroboros-network
    - safe
    - scientific
    - shelley-spec-ledger
    - text
    - time
    - time-extra
    - typed-protocols
    - unordered-containers
    - vector
    - wai
    - wai-routes
    - wai-websockets
    - warp
    - websockets

executables:
  ogmios:
    main: Main.hs
    source-dirs: app
    ghc-options: *ghc-options-test
    when:
      condition: flag(production)
      ghc-options:
      - -Werror
      - -O2
      - -with-rtsopts=-A250m
      - -with-rtsopts=-N3
      - -with-rtsopts=-T
    dependencies:
    - ogmios
    - text

tests:
  unit:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options:
    - -Wcompat
    - -fwarn-redundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - cardano-client
    - cardano-slotting
    - generic-arbitrary
    - hedgehog-quickcheck
    - hspec
    - hspec-json-schema
    - json-wsp
    - ogmios
    - ouroboros-consensus
    - ouroboros-consensus-byron
    - ouroboros-consensus-cardano
    - ouroboros-consensus-cardano-test
    - ouroboros-consensus-shelley
    - ouroboros-network
    - QuickCheck
    - shelley-spec-ledger
    - shelley-spec-ledger-test
    - text
