_config: !include ".hpack.config.yaml"

name:                ogmios
version:             0
stability:           stable
github:              "cardanosolutions/ogmios"
license:             MPL-2.0
author:              "KtorZ <matthias.benkort@gmail.com>"
maintainer:          "matthias.benkort@gmail.com"
copyright:           "2020-2024 KtorZ"
description:         Please see the README on GitHub at <https://github.com/cardanosolutions/ogmios/tree/master/server#ogmios-server>
synopsis:            A JSON/RPC-2.0 WebSocket client for cardano-node
category:            Web

extra-source-files:
- static/*
- static/assets/*

dependencies:
- base >= 4.7 && < 5

default-extensions: *default-extensions

flags:
  production:
    description: Compile executables for production.
    default: False
    manual: True

library:
  source-dirs: src
  ghc-options: *ghc-options-lib
  when:
    condition: flag(production)
    ghc-options:
    - -Werror
    - -O2
  dependencies:
    - aeson
    - array
    - async
    - attoparsec-aeson
    - base16
    - base58-bytestring
    - bech32
    - bech32-th
    - binary
    - bytestring
    - cardano-crypto
    - cardano-crypto-class
    - cardano-crypto-wrapper
    - cardano-data
    - cardano-ledger-allegra
    - cardano-ledger-alonzo
    - cardano-ledger-api
    - cardano-ledger-babbage
    - cardano-ledger-binary
    - cardano-ledger-byron
    - cardano-ledger-conway
    - cardano-ledger-core
    - cardano-ledger-mary
    - cardano-ledger-shelley
    - cardano-protocol-tpraos
    - cardano-slotting
    - cardano-strict-containers
    - cborg
    - containers
    - contra-tracer
    - contra-tracers
    - directory
    - ekg-core
    - fast-bech32
    - file-embed
    - filepath
    - formatting
    - generic-lens
    - git-th
    - http-client
    - http-types
    - io-classes
    - io-sim
    - iohk-monitoring
    - iproute
    - json-rpc
    - lens-aeson
    - memory
    - mtl
    - optparse-applicative
    - ouroboros-consensus
    - ouroboros-consensus-cardano
    - ouroboros-consensus-protocol
    - ouroboros-network
    - ouroboros-network-api
    - ouroboros-network-framework
    - ouroboros-network-ogmios
    - ouroboros-network-protocols
    - plutus-ledger-api
    - prettyprinter
    - profunctors
    - prometheus
    - relude
    - safe
    - safe-exceptions
    - scientific
    - serialise
    - small-steps
    - sop-extras
    - strict-sop-core
    - stm
    - text
    - time
    - time-manager
    - transformers
    - typed-protocols
    - unix
    - vector
    - wai
    - wai-websockets
    - warp
    - yaml
    - websockets

executables:
  ogmios:
    main: Main.hs
    source-dirs: app
    ghc-options: *ghc-options-executable
    when:
      condition: flag(production)
      ghc-options:
      - -O2
      - -Werror
      - '"-with-rtsopts=-A100m -T -N2"'
    dependencies:
    - ogmios

tests:
  unit:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options: *ghc-options-test
    dependencies:
    - aeson
    - aeson-pretty
    - bytestring
    - cardano-ledger-alonzo
    - cardano-ledger-api
    - cardano-ledger-binary
    - cardano-ledger-core
    - cardano-ledger-shelley
    - cardano-ledger-shelley-test
    - cardano-slotting
    - containers
    - directory
    - file-embed
    - generic-arbitrary
    - generics-sop
    - hspec
    - hspec-json-schema
    - io-classes
    - io-sim
    - json-rpc
    - lens-aeson
    - ogmios
    - ouroboros-consensus
    - ouroboros-consensus-cardano
    - ouroboros-consensus-cardano:unstable-cardano-testlib
    - ouroboros-consensus-protocol
    - ouroboros-network-api
    - ouroboros-network-framework
    - ouroboros-network-ogmios
    - ouroboros-network-protocols
    - QuickCheck
    - random
    - strict-sop-core
    - template-haskell
    - text
    - time
    - typed-protocols
    build-tools:
    - hspec-discover
