resolver: resolver.yaml

compiler: ghc-8.10.4 # Simply for reference, already inferred from the resolver.

# Generate files required by weeder
# See https://github.com/ndmitchell/weeder/issues/53
ghc-options: {"$locals": -ddump-to-file -ddump-hi}

packages:
- .
- modules/cardano-client
- modules/fast-bech32
- modules/git-th
- modules/hspec-json-schema
- modules/json-wsp
- modules/json-via-show

flags:
  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false
