_config: !include "../../.hpack.config.yaml"

name:                git-th
version:             1.1.0
github:              "cardanosolutions/ogmios"
license:             MPL-2.0
author:              "KtorZ <matthias.benkort@gmail.com>"
maintainer:          "matthias.benkort@gmail.com"
copyright:           "2020-2021 KtorZ"
description:         Please see the README on GitHub at <https://github.com/cardanosolutions/ogmios/tree/master/server/modules/git-th>
synopsis:            Compile-time helpers to access git informations.
category:            Development

extra-source-files:
- LICENSE
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

default-extensions: *default-extensions

library:
  source-dirs: src
  ghc-options: *ghc-options-lib
  dependencies:
    - process
    - template-haskell
  system-build-tools:
  - git

tests:
  integration:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options: *ghc-options-test
    dependencies:
    - git-th
    - hspec
    - template-haskell
    - temporary
    build-tools:
    - hspec-discover
