_config: !include "../../.hpack.config.yaml"

name:                json-wsp
version:             2.0.0
github:              "cardanosolutions/ogmios"
license:             MPL-2.0
author:              "KtorZ <matthias.benkort@gmail.com>"
maintainer:          "matthias.benkort@gmail.com"
copyright:           "2020-2021 KtorZ"
description:         Please see the README on GitHub at <https://github.com/cardanosolutions/ogmios/tree/master/server/modules/json-wsp>
synopsis:            An implementation of JSON-WSP in Haskell
category:            Web

extra-source-files:
- LICENSE
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

default-extensions: *default-extensions

library:
  source-dirs: src
  ghc-options: *ghc-options-lib
  dependencies:
    - aeson
    - bytestring
    - text

tests:
  unit:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options: *ghc-options-test
    dependencies:
    - aeson
    - hspec
    - json-wsp
    build-tools:
    - hspec-discover
