_config: !include "../../.hpack.config.yaml"

name:                fast-bech32
version:             1.0.0
github:              "cardanosolutions/ogmios"
license:             MPL-2.0
author:              "KtorZ <matthias.benkort@gmail.com>"
maintainer:          "matthias.benkort@gmail.com"
copyright:           "2021 KtorZ"
description:         Please see the README on GitHub at <https://github.com/cardanosolutions/ogmios/tree/master/server/modules/fast-bech32>
synopsis:            Fast implementation of the Bech32 encoding format.
category:            Codec

extra-source-files:
- LICENSE
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

default-extensions: *default-extensions

library:
  source-dirs: src
  ghc-options: *ghc-options-lib
  when:
    condition: true
    ghc-options:
    - -O2
  dependencies:
    - bytestring
    - relude
    - text

benchmarks:
  encoding:
    main: Encoding.hs
    source-dirs: bench
    ghc-options: *ghc-options-test
    dependencies:
    - bytestring
    - criterion
    - bech32
    - fast-bech32
    - random-bytestring

tests:
  unit:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options: *ghc-options-test
    dependencies:
    - base16
    - bech32
    - bytestring
    - fast-bech32
    - hspec
    - QuickCheck
    - text
    build-tools:
    - hspec-discover
