_config: !include "../../.hpack.config.yaml"

name:                time-extra
version:             1.0.0
github:              "KtorZ/cardano-ogmios"
license:             MPL-2.0
author:              "KtorZ <matthias.benkort@gmail.com>"
maintainer:          "matthias.benkort@gmail.com"
copyright:           "2020 KtorZ"
description:         Please see the README on GitHub at <https://github.com/KtorZ/ogmios>
synopsis:            Some extra functions for the time package.
category:            Utilities

extra-source-files:
- LICENSE
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

default-extensions: *default-extensions

library:
  source-dirs: src
  ghc-options: *ghc-options-lib
  dependencies:
    - async
    - time

tests:
  unit:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options: *ghc-options-test
    dependencies:
    - hspec
    - QuickCheck
    - time
    - time-extra
