_config: !include "../../.hpack.config.yaml"

name:                cardano-client
version:             1.0.0
github:              "cardanosolutions/ogmios"
license:             MPL-2.0
author:              "KtorZ <matthias.benkort@gmail.com>"
maintainer:          "matthias.benkort@gmail.com"
copyright:           "2020-2021 KtorZ"
description:         Please see the README on GitHub at <https://github.com/cardanosolutions/ogmios/tree/master/server/modules/cardano-client>
synopsis:            Utilities to build a cardano client using the Ouroboros mini-protocols
category:            Cardano

extra-source-files:
- LICENSE
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

default-extensions: *default-extensions

library:
  source-dirs: src
  ghc-options: *ghc-options-lib
  dependencies:
    - aeson
    - bytestring
    - cardano-ledger-byron
    - cardano-ledger-core
    - cardano-slotting
    - cborg
    - containers
    - contra-tracer
    - io-classes
    - iohk-monitoring
    - network-mux
    - ouroboros-consensus
    - ouroboros-consensus-protocol
    - ouroboros-consensus-byron
    - ouroboros-consensus-cardano
    - ouroboros-consensus-shelley
    - ouroboros-network
    - ouroboros-network-framework
    - typed-protocols
    - typed-protocols-cborg
  build-tools:
  - hspec-discover
