name: Coding Style

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
    tags: [ "*.*.*" ]

jobs:
  server:
    strategy:
      matrix:
        os: [ubuntu-latest]

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v2.3.3

    - name: 🔬 hlint
      env:
        PACKAGE: hlint
        REPOSITORY: ndmitchell/hlint
        PLATFORM: x86_64-linux
        RELEASE: v3.2
        VERSION: 3.2
      run: |
        cd server
        curl -sSL https://raw.github.com/KtorZ/cardano-ogmios/master/.github/scripts/from-github.sh | sh -s src test app -h .hlint.yaml

    - name: 🧐 stylish-haskell
      env:
        PACKAGE: stylish-haskell
        REPOSITORY: jaspervdj/stylish-haskell
        PLATFORM: linux-x86_64
        RELEASE: v0.11.0.0
        VERSION: v0.11.0.0
      run: |
        cd server
        curl -sSL https://raw.github.com/KtorZ/cardano-ogmios/master/.github/scripts/from-github.sh | sh -s $(find src test app -type f -name '*.hs' ! -path '*.stack-work*') -i -c .stylish-haskell.yaml
        if [ -z "$(git status --porcelain)" ]; then
            echo "No style errors detected."
        else
            echo "Style errors detected:"
            git diff
            exit 1
        fi

    - name: 🐳 hadolint
      uses: brpaz/hadolint-action@1.4.0
      with:
        dockerfile: "server/Dockerfile"
