name: User Guide

on:
  push: { "branches": [ "master" ] }
  pull_request: { "branches": [ "master" ] }

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: 📥 Checkout repository
      uses: actions/checkout@v2.3.3
      with:
        submodules: true

    - name: 🧰 Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.15.0

    - name: 🧰 Download Hugo
      run: |
        curl -L https://github.com/gohugoio/hugo/releases/download/v0.76.5/hugo_extended_0.76.5_Linux-64bit.tar.gz | tar xz

    - name: 🔨 Build TypeScript Doc
      working-directory: clients/TypeScript
      run: |
        yarn install --frozen-lockfile --non-interactive --logevel=error
        yarn build
        yarn docs

    - name: 📸 Build Static Website
      shell: bash
      working-directory: docs
      run: |
        ../hugo -t learn --minify
        echo "ogmios.dev" > public/CNAME

    - name: 📘 Publish Artifacts
      if: matrix.os == 'ubuntu-latest' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/public
        enable_jekyll: false
