name: W.I.P

on:
  push:
    branches: [ "KtorZ/docker" ]

jobs:
  server:
    runs-on: ubuntu-latest
    steps:

    - name: 📥 Checkout repository
      uses: actions/checkout@v2.3.3

    - name: 💾 Cache Containers
      id: cache
      uses: actions/cache@v2.1.1
      with:
        path: ./data
        key: cardano-node

    - name: 🔨 Overwrite docker-compose.yml
      shell: bash
      run: |
        sed -i "s@node-db:/data@./data:/data@" docker-compose.yml

    - name: 💽 Run Container
      env:
        NETWORK: testnet
      run: |
        docker-compose up -d cardano-node
        sleep 60
        docker-compose logs cardano-node
        docker-compose down
